name: Main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}@main-${{ github.ref }}
  cancel-in-progress: true

jobs:

  infos:
    name: Infos
    runs-on: ubuntu-22.04
    outputs:
      package-namespace: ${{ steps.infos.outputs.namespace }}
    steps:
      - name: Some infos
        id: infos
        run: |
          echo github.run_id is ${{ github.run_id }}
          echo github.ref is ${{ github.ref }}
          echo github.head_ref is ${{ github.head_ref }}
          echo github.ref_name is ${{ github.ref_name }}
          echo github.sha is ${{ github.sha }}
          echo github.event_name is ${{ github.event_name }}
          echo github.event.pull_request.user.login is ${{ github.event.pull_request.user.login }}
          echo github.event.action is ${{ github.event.action }}
          echo github.event.repository_owner is ${{ github.repository_owner }}
          NAMESPACE=${{ github.repository || github.event.repository }}
          NAMESPACE_LC=${NAMESPACE,,}
          echo "namespace=${NAMESPACE_LC}" >> $GITHUB_OUTPUT
          echo namespace is ${NAMESPACE_LC}

  build_ubuntu:
    name: Build in Ubuntu
    needs:
      - infos
    uses: ./.github/workflows/build-ubuntu.yml
    secrets: inherit
    with:
      namespace: ${{ needs.infos.outputs.package-namespace }}
      artifact_name: senscord-${{ github.run_id }}

  checkpoint_success:
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    needs:
      - build_ubuntu
    steps:
      - name: Check all previous jobs finished correctly
        run: |
          if [ "${{ needs.build_ubuntu.result }}" = "success" ]; then
            echo Requested jobs finished successfully. This PR can be merged
          else
            echo Requested jobs are failing. This PR can not be merged
            exit 1
          fi

  release_on_tag:
    if: >-
      needs.checkpoint_success.result == 'success' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/')

    needs:
      - build_ubuntu
      - checkpoint_success

    runs-on: ubuntu-24.04

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: senscord-${{ github.run_id }}
          path: artifacts

      - name: Create draft GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          files: artifacts/*.deb
